apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-runtime
  namespace: nifi
data:
  # Reemplazar por el FQDN real del cliente
  nifi-web-proxy-host: "nifi.apps.cliente.local"
  nifi-cluster-load-balance-host: "nifi.apps.cliente.local"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nifi
  namespace: nifi
spec:
  rules:
    - host: nifi.apps.cliente.local
