# ─────────────────────────────────────────────
#  Secret — credenciales y contraseñas TLS
#
#  IMPORTANTE: Cambia los valores antes de aplicar.
#  Para codificar en base64: echo -n 'mipassword' | base64
#
#  Valores por defecto (¡solo para desarrollo!):
#    NIFI_USERNAME: admin
#    NIFI_PASSWORD: AdminPassword123!
#    KEYSTORE_PASSWORD: keystorepass
#    TRUSTSTORE_PASSWORD: truststorepass
#    NIFI_SENSITIVE_PROPS_KEY: NiFiSensProps1234!  (mín. 12 chars, igual en todos los nodos)
# ─────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: nifi-credentials
  namespace: nifi
type: Opaque
data:
  # admin
  NIFI_USERNAME: YWRtaW4=
  # AdminPassword123!   (mínimo 12 caracteres exigido por NiFi 2.x)
  NIFI_PASSWORD: QWRtaW5QYXNzd29yZDEyMyE=
  # keystorepass
  KEYSTORE_PASSWORD: a2V5c3RvcmVwYXNz
  # truststorepass
  TRUSTSTORE_PASSWORD: dHJ1c3RzdG9yZXBhc3M=
  # NiFiSensProps1234!  — clave de cifrado de propiedades sensibles (obligatoria en cluster)
  NIFI_SENSITIVE_PROPS_KEY: TmlGaVNlbnNQcm9wczEyMzRcIQ==
